spring:
  datasource:
    url: jdbc:postgresql://tepoz-db.ct4u4640q2zk.us-east-1.rds.amazonaws.com:5432/postgres
    username: "{cipher}e2c401be23bd30703e600f00d54236faa10cda69b53e199e461bac0b6101ee6a"
    password: "{cipher}db5b695d20d730a704db53489095976f75b53eca66a12f63dcc419f69260013c"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
